name: Compila Código C++ 
on:
  push:
    branches:
      - master  # Ejecutará cuando haya un push a la rama master
  pull_request:
    branches:
      - master  # Ejecutará en pull request a la rama master

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos un entorno Ubuntu para compilar
    timeout-minutes: 10  # Ajusta según sea necesario
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Obtiene tu código desde GitHub

      - name: Set up C++ build environment
        run: sudo apt-get update && sudo apt-get install -y g++  # Instala el compilador g++

      - name: Compile code
        run: |
          g++ -o ConectaCuatro src/ConectaCuatro.cpp  # Compila el código fuente
          chmod +x ConectaCuatro  # Asegúrate de que el ejecutable sea ejecutable
          echo "Compilación exitosa. Ejecutando el programa..."
          ./ConectaCuatro  # Ejecuta el programa compilado

